config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'homes#top'
  get "/home/about" => "homes#about", as: "about"

  resources :users, only: [:index, :show, :edit, :update]
  resources :books, only: [:index, :show, :create, :edit, :update, :destroy]
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :image
  belongs_to :user

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_fill: [width, height]).processed
  end

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200}

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         authentication_keys: [:name]

  

  has_one_attached :profile_image

  def get_image(width = 100, height = 100)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_fill: [width, height]).processed
  end
 
  has_many :books, dependent: :destroy

  validates :name, presence: true, uniqueness:true, length: { minimum: 2 , maximum: 20 }
  validates :introduction, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  def after_sign_up_path_for(resource)
    user_path(resource)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :name])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!

    
  def index
    @book = Book.new
    @books  = Book.all
    @user = current_user
  end
  
  def show
    @book = Book.find(params[:id])
    @user = @book.user    
    @books = @user.books
    @book_new = Book.new
  end


  def create
    @book = current_user.books.build(book_params)
    @user = current_user
    @books = Book.all
    if @book.save
      redirect_to @book, notice: "You have created book successfully"
    else 
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
    unless @book.user.id == current_user.id
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    unless @book.user.id == current_user.id
      redirect_to books_path
    end
    if @book.update(book_params)
      redirect_to @book, notice: "Book was successfully update."
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    respond_to do |format|
      format.html {redirect_to books_path, notice: "Book was successfully deleted."}
    end

  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :user_id)
  end
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
    @user = current_user
    @books = Book.all
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
    unless @user.id == current_user.id
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    unless @user.id == current_user.id
      redirect_to user_path(current_user)
    end
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "You have updated user successfully."
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :introduction, :profile_image)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_helper.rb
module BookHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
  <h1>Editing Book</h1>

<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
  <% end %>

<%= form_with model: @book do |f| %>

  <h4>Title</h4>
  <%= f.text_field :title %>

  <h4>Opinion</h4>
  <%= f.text_area :body %><br>

  <%= f.submit "Update Book", class: "btn btn-primary" %>

  <p><%= link_to "Show", book_path(@book) %></p>
  <span><%= link_to "Back", books_path %></span>

<% end %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>件のエラーが発生しました
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/list',user:@user ,book:@book %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>

      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user) do %>
                  <%= image_tag @user.get_image(100,100) %>
                <% end %>
              </td>
              <td>
                <%= link_to book_path(book) do %>
                  <%= book.title %>
                <% end %>
              </td>
              <td><%= book.body %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/list',user:@book.user, book:@book_new %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>

      <table class="table table-hover table-inverse">
        <thead>
          <td>
            <td>
              <%= link_to user_path(@book.user), class: "d-block", style:"width: 100px;" do %>
                <%= image_tag @book.user.get_image(100,100), class:"rounded", style: "width: 100px; height: 100px; object-fit: cover;" %>
                
                <%= @book.user.name %>
                </span>
              <% end %>
            </td>
          </td>
          <td>
            <td>
              <%= link_to book_path(@book) do %>
                  <%= @book.title %>
              <% end %>
            </td>
          </td>
          <td>
            <td><%= @book.body %></td>
          </td>
          <td>
          <% if @book.user == current_user %>
            <%= link_to "Edit", edit_book_path(@book), class: "btn btn-success" %>
            <%= link_to "Destroy", book_path(@book), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-success" %>
          <% end %>
          </td>
        </thead>
      </table>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">Welcome to
      <i class="fas fa-book"></i>
      <strong>Bookers</strong>!
    </h1>
  </div>
</div>

app/views/homes/top.html.erb
<div>
  <%= flash[:notice] %>
</div>

<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fa-solid fa-book"></i><strong>Bookers</strong> !!</h1>
      <p>in <i class="fa-solid fa-book"></i><strong>Bookers</strong>,</p>
      <p>you can share and exchange your opinions , inpressions , and emotions</p>
      <p>about various books!</p>

      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to "Log in", new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3" %>
        </div>
        <div class="row">
          <%= link_to "Sign up", new_user_registration_path, class: "btn btn-success btn-sm btn-block" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container mt-5">
    <div class="row">
      <div class="mx-auto">
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
	   <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
	     <div class="container">
	       <a class="navbar-brand" href="/"><span>Bookers</span></a>
	       <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
	        <span class="navbar-toggler-icon"></span>
	       </button>
	      <div class="collapse navbar-collapse" id="navbarNavDropdown">
	        <ul class="navbar-nav ml-auto">
					  <% if user_signed_in? %>
	           <li>
	            <%= link_to new_user_session_path, class:"nav-link text-light" do %>
	             <i class="fa-solid fa-house"></i> Home
	            <% end %>
	           </li>
						 <li>
						  <%= link_to users_path, class:"nav-link text-light" do %>
							 <i class="fa-solid fa-users"></i> Users
							<% end %>
						 </li>
						 <li>
						  <%= link_to books_path, class:"nav-link text-light" do %>
							 <i class="fa-solid fa-book-open"></i> Books
							<% end %>
						 </li>
						 <li>
						  <%= link_to destroy_user_session_path, method: :delete, class:"nav-link text-light" do %>
							 <i class="fa-solid fa-right-from-bracket"></i> Log out
							<% end %>
						 </li>
						<% else %>
						 <li>
	            <%= link_to root_path, class:"nav-link text-light" do %>
	             <i class="fa-solid fa-house"></i> Home
	            <% end %>
	           </li>
	           <li>
	            <%= link_to about_path, class:"nav-link text-light" do %>
	             <i class="fa-solid fa-link"></i> About
	            <% end %>
	           </li>
	           <li>
	            <%= link_to new_user_registration_path, class:"nav-link text-light" do %>
	             <i class="fa-solid fa-user-plus"></i> Sign up
	            <% end %>
	           </li>
	           <li>
	            <%= link_to new_user_session_path, class:"nav-link text-light" do %>
	             <i class="fa-solid fa-right-to-bracket"></i> Log in
	            <% end %>
						 </li>
						<% end %>
					</ul>
				</div>
			 </div>
		</nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/8d58eb4af8.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <main>
       <div>
        <%= flash[:notice] %>
       </div>
        <%= yield %>
     
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/users/_list.html.erb
      <h2>User info</h2>

      <table class="table">
      <tr>
        <%= image_tag user.get_image(100,100) %>
      </tr>
      <tr>
        <th>name:<%= user.name %></th>
      </tr>
      <tr>
        <th>introduction:<%= user.introduction %></th>
      </tr>
      </table>
      <div class="row">
        <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
          <i class="fas fa-user-cog"></i>
        <% end %>
      </div>
      <h2 class="mt-3">New book</h2>
      <%= form_with model: book, local: true do |f| %>
        <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :title, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :body, "Opinion" %>
          <%= f.text_field :body, class: "form-control" %>
        </div>
        <div class="form-group mt-2">
          <%= f.submit "Create Book", class: "btn btn-success" %>
        </div>
      <% end %>
    
    

app/views/users/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
  <h1>User info</h1>

<% if @user.errors.any? %>
  <%= @user.errors.count %>errors prohibited this book from being saved:
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
  <% end %>

<%= form_with model: @user, local: true do |f| %>

  <h4>Name</h4>
  <%= f.text_field :name %>

  <h4>Image</h4>
  <%= f.file_field :profile_image, placeholder: "ファイルを選択" %>

  <h4>Introduction</h4>
  <%= f.text_area :introduction %><br>

  <%= f.submit "Update User", class: "btn btn-primary" %>

<% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'list',user:@user ,book:@book %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>

      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th>image</th>
            <th></th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= image_tag book.user.get_image(100,100) %>
              </td>
              <td></td>
              <td><%= book.user.name %></td>
              <td>
                <%= link_to "Show", user_path(book.user) %>
              </td>
            </tr>
          <% end %>       
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'list',user:@user, book:@book %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>

      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(@user) do %>
                  <%= image_tag book.user.get_image(100, 100) %>
                <% end %>
              </td>
              <td>
                <%= link_to book_path(book) do %>
                  <%= book.title %>
                <% end %>
              </td>
              <td><%= book.body %></td>
            </tr>
          <% end %>       
        </tbody>
      </table>
    </div>
    
  </div>
</div>